MODULES := mdc
mdc-objs :=	mdc_request.o \
		mdc_reint.o \
		lproc_mdc.o \
		mdc_lib.o \
		mdc_locks.o \
		mdc_changelog.o \
		mdc_dev.o

EXTRA_DIST = $(mdc-objs:.o=.c) mdc_internal.h

include /Users/crb002/github/lustre-release/Rules
