obj-m += fid/
obj-m += obdclass/
obj-m += ptlrpc/
obj-m += obdecho/
obj-m += mgc/
obj-m += tests/kernel/

#obj-m += ost/ mgs/ mdt/ mdd/ ofd/ quota/ osp/ lod/ lfsck/
obj-m += lov/ osc/ mdc/ lmv/ llite/ fld/
#obj-m += osd-ldiskfs/
#obj-m += osd-zfs/


include /Users/crb002/github/lustre-release/Rules
