name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: getclang
      run: sudo apt-get install -y clang clang-tools
    - name: make_config
      run: bash autogen.sh 
    - name: configure
      run: ./configure
    - name: make
      run: scan-build make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
